[project]
name = "russian-nlp-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
# requires-python = ">=3.13"
dependencies = [
    "six>=1.17.0",
    "trankit>=1.1.1",
]
