[project]
name = "trankit-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "six>=1.17.0",
    "tomli>=2.2.1",
    "trankit==1.1.2",
]

[tool.uv]
override-dependencies = ["transformers<4.50", "numpy<2"]
