[project]
name = "natasha-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "natasha>=1.6.0",
    "setuptools>=80.9.0",
]
